### ISSUE TITLE
Keyboard shortcut without the icon?

### ISSUE THREAD

**Issue by Gittyperson** [JustOff/emoji-helper#1]
Thanks for this Pale Moon release!

Just a question: is it possible to still use the keyboard shortcut without having the icon present on a toolbar? The shortcut seems to stop working if I remove the icon (Pale Moon 27.4.2 x64, W10). Perhaps it's a general browser restriction.

(btw it'd be nice if the icon could be user-selected)

**Comment by JustOff** [comment]
Visible toolbar button is required because the Emoji sheet is attached to it.
